config/routes.rb
resources :scheduled_emails do
  resources :send_schedules
end

app/models/scheduled_email.rb
class ScheduledEmail < ActiveRecord::Base
  has_many :send_schedules, :dependent => :destroy

  def next_send
    dates = []
    send_schedules.each do |schedule|
      dates << schedule.next_send
    end
    return dates.compact.uniq.sort.reject{ |d| d < Date.today }.first
  end

end

app/controllers/scheduled_emails_controller.rb
class ScheduledEmailsController < ApplicationController
  unloadable
  
  before_action :require_admin

  def index
    @scheduled_emails = ScheduledEmail.all
  end

  def new
    @scheduled_email = ScheduledEmail.new
  end

  def create
    @scheduled_email = ScheduledEmail.new(scheduled_email_params)
    if @scheduled_email.save
      redirect_to edit_scheduled_email_path(@scheduled_email)
    else
      render 'new'
    end
  end

  def edit
    @scheduled_email = ScheduledEmail.find(params[:id])
  end

  def update
    @scheduled_email = ScheduledEmail.find(params[:id])
    if @scheduled_email.update(scheduled_email_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @scheduled_email = ScheduledEmail.find(params[:id])
    @scheduled_email.destroy
    redirect_to action: 'index'
    flash[:notice] = l(:notice_successful_delete)
  end
  
  private
    def scheduled_email_params
      params.require(:scheduled_email).permit(:name, :sender, :recipient, :cc, :bcc, :reply_to, :subject, :message)
    end
end

app/helpers/scheduled_emails_helper.rb
module ScheduledEmailsHelper

  def list_weekdays
    ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
  end

  def list_months
    ['January','February','March','April','May','June','July','August','September','October','November','December']
  end

end

app/views/scheduled_emails/_action_menu.html.erb
<div class="contextual">
  <%= link_to 'New Scheduled Email', new_scheduled_email_path, :class => 'icon icon-add' %>
</div>

app/views/scheduled_emails/_scheduled_email_menu.html.erb
<div class="contextual">
  <%= link_to l(:label_back), { controller: 'scheduled_emails', action: 'index' }, :class => 'icon icon-reload' %>
</div>

app/views/scheduled_emails/edit.html.erb
<%= render :partial => 'scheduled_email_menu' %>

<h2>Edit <%= @scheduled_email.name %></h2>

<%= labelled_form_for @scheduled_email do |f| %>
  <div class='box tabular'>
    <p>
      <%= f.text_field :name, required: true %>
    </p>
    <p>
      <%= f.text_field :sender %>
    </p>
    <p>
      <%= f.text_field :recipient, required: true %>
    </p>
    <p>
      <%= f.text_field :subject, required: true %>
    </p>
    <p>
      <%= f.label_for_field :message, required: true %>
      <%= content_tag 'span', :id => "message_and_toolbar" do %>
        <%= f.text_area :message,
                   :cols => 60,
                   :rows => [[10, @scheduled_email.message.to_s.length / 50].max, 20].min,
                   :accesskey => accesskey(:edit),
                   :class => 'wiki-edit',
                   :no_label => true %>
      <% end %>
    </p>
    <%= wikitoolbar_for 'scheduled_email_message' %>
  </div>
  <p>
    <%= f.submit l(:button_save_email) %>
  </p>
<% end %>

<h3>Schedules</h3>

<div class="autoscroll">
  <% if @scheduled_email.send_schedules.any? %>
    <table class="list">
      <thead><tr>
        <th><%= l(:next_email) %></th>
        <th><%= l(:field_month_day) %></th>
        <th><%= l(:field_week_day) %></th>
        <th><%= l(:field_month) %></th>
        <th></th>
      </tr></thead>
      <tbody>
        <% for send_schedule in @scheduled_email.send_schedules %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td><%= send_schedule.next_send %></td>
            <td><%= send_schedule.day_text %></td>
            <td>
              <% send_schedule.week_text.each do |wt| %>
                <%= wt %><br>
              <% end %>
            </td>
            <td><%= send_schedule.month_text %></td>
            <td><%= link_to l(:button_delete), scheduled_email_send_schedule_path(@scheduled_email, send_schedule), :method => :delete, :data => {:confirm => l(:text_are_you_sure)} ,:class => 'icon icon-del' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%= l(:not_scheduled) %>
  <% end %>
</div>

<h4>Add new schedule</h4>

<%= labelled_form_for([@scheduled_email, @scheduled_email.send_schedules.build]) do |f| %>
  <div class='box tabular'>
    <p>
      <%= f.select :month_day, (1..31).to_a, { :include_blank => false }, { :style => 'min-width: 130px;', :multiple => true, :size => 10 } %>
    </p>
    <p>
      <%= f.select :week, (1..5).to_a, { :include_blank => false }, { :style => 'min-width: 130px;', :multiple => true, :size => 5 } %>
    </p>
    <p>
      <%= f.select :week_day, list_weekdays, { :include_blank => false }, { :style => 'min-width: 130px;', :multiple => true, :size => 7 } %>
    </p>
    <p>
      <%= f.select :month, list_months, { :include_blank => false, :required => true }, { :style => 'min-width: 130px;', :multiple => true, :size => 10 } %>
    </p>
    <p>
      <%= f.submit l(:button_add_schedule) %>
    </p>
  </div>
<% end %>

app/views/scheduled_emails/index.html.erb
<%= render :partial => 'action_menu' %>

<h2>Scheduled Emails</h2>

<div class="autoscroll">
<table class="list">
  <thead><tr>
    <th><%= l(:field_name) %></th>
    <th><%= l(:field_recipient)%></th>
    <th><%= l(:field_subject) %></th>
    <th><%= l(:next_email) %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for scheduled_email in @scheduled_emails %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= link_to scheduled_email.name, edit_scheduled_email_path(scheduled_email) %></td>
    <td><%= scheduled_email.recipient %></td>
    <td><%= scheduled_email.subject %></td>
    <td><%= scheduled_email.next_send %></td>
    <td><%= link_to l(:button_delete), scheduled_email_path(scheduled_email), :method => :delete, :data => {:confirm => l(:text_are_you_sure)} ,:class => 'icon icon-del' %></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<%= render :partial => 'action_menu' %>

app/views/scheduled_emails/new.html.erb
<%= render :partial => 'scheduled_email_menu' %>

<h2>New Scheduled Email</h2>

<%= labelled_form_for @scheduled_email do |f| %>
  <div class='box tabular'>
    <p>
      <%= f.text_field :name, required: true %>
    </p>
    <p>
      <%= f.text_field :sender %>
    </p>
    <p>
      <%= f.text_field :recipient, required: true %>
    </p>
    <p>
      <%= f.text_field :subject, required: true %>
    </p>
    <p>
      <%= f.label_for_field :message, required: true %>
      <%= content_tag 'span', :id => "message_and_toolbar" do %>
        <%= f.text_area :message,
                   :cols => 60,
                   :rows => [[10, @scheduled_email.message.to_s.length / 50].max, 20].min,
                   :accesskey => accesskey(:edit),
                   :class => 'wiki-edit',
                   :no_label => true %>
      <% end %>
    </p>
    <%= wikitoolbar_for 'scheduled_email_message' %>
  </div>
  <p>
    <%= f.submit l(:button_submit) %>
  </p>
<% end %>